version: '3.8'
services:
  app:
    extends:
      file: docker-compose-administration-base.yml
      service: app
    container_name: administration-local
    ports:
      - "8108:8080"
    environment:
      - HIBERNATE_DEFAULT_SCHEMA=local_admins
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-local:8761/eureka/
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - nervus-network

networks:
  nervus-network:
    external: true