version: '3.8'
services:
  administration-staging:
    image: ghcr.io/nervus-tech/nervus-administration:v1.0.0-staging
    container_name: administration-staging
    ports:
      - "8109:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - HIBERNATE_DEFAULT_SCHEMA=staging_admins
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - nervus-infrastructure_default
    # depends_on removed - expects shared infrastructure Postgres
  # Postgres service removed - expects shared infrastructure 

networks:
  nervus-infrastructure_default:
    external: true 